### ISSUE TITLE
[shopify-api-timeout error]

### ISSUE THREAD

**Issue by karunyaBobby** [ShopifyExtras/PHP-Shopify-API-Wrapper#62]
[31-May-2017 09:56:04 Etc/GMT] PHP Fatal error: Uncaught exception 'ShopifyCurlException' with message 'Connection timed out after 30001 milliseconds' in /home/avishopr/public_html/playground/mysqg/M-Sendy/shopify.php:117
Stack trace:
#0 /home/avishopr/public_html/playground/mysqg/M-Sendy/shopify.php(36): ShopifyClient->curlHttpApiRequest('POST', 'https://sellerb...', '', 'client_id=95c6c...', Array)
#1 /home/avishopr/public_html/playground/mysqg/M-Sendy/authorization.php(16): ShopifyClient->getAccessToken('35e185a7821981e...')
#2 {main}
thrown in /home/avishopr/public_html/playground/mysqg/M-Sendy/shopify.php on line 117

Earlier it was working. now its throwing time out error. please let me know, what change need to do

**Comment by karunyaBobby** [comment]
Uncaught exception 'ShopifyCurlException' with message 'Failed to connect to sellerblog.myshopify.com port 443

**Comment by karunyaBobby** [comment]
Resource id #4Connection timed out after 30000 milliseconds
